package main

// ShipMetadata includes the maps used for categorizing ships and ship statuses.
type ShipMetadata struct {
	ShipType  map[int]ShipTypeClass `json:"shipType"`
	ShipGroup map[int]ShipTypeGroup `json:"shipGroup"`
	NavStatus map[int]string        `json:"navStatus"`
}

// NavStatus is a map of navigation status IDs to their string descriptors.
// Descriptions have been adjusted for use in ship infowindow.
// Reference: https://www.navcen.uscg.gov/ais-class-a-reports
var NavStatus = map[int]string{
	0:  "Under way using engine",
	1:  "At anchor",
	2:  "Not under command",
	3:  "Restricted maneuverability",
	4:  "Constrained by her draught",
	5:  "Moored",
	6:  "Aground",
	7:  "Engaged in fishing",
	8:  "Under way sailing",
	9:  "Reserved",
	10: "Reserved",
	11: "Towing astern",
	12: "Pushing or towing alongside",
	13: "reserved for future use",
	14: "AIS-SART, MOB-AIS, EPIRB-AIS",
	15: "Not defined",
}

// ShipTypeGroup is used by the ShipTypeGroups map to store category and color attributes for each ship group.
type ShipTypeGroup struct {
	Category string `json:"category"`
	Color    string `json:"color"`
}

// ShipTypeGroups defines ship category and color based on the group Ids referenced by the ShipTypes map.
var ShipTypeGroups = map[int]ShipTypeGroup{
	0: {Category: "Cargo", Color: "#cc7b0a"},
	1: {Category: "Fishing", Color: "#0394ad"},
	2: {Category: "Military", Color: "#02115e"},
	3: {Category: "Not Available", Color: "#04dbcd"},
	4: {Category: "Other", Color: "#949494"},
	5: {Category: "Passenger", Color: "#dbdb04"},
	6: {Category: "Pleasure Craft", Color: "#b004aa"},
	7: {Category: "Tanker", Color: "#a81803"},
	8: {Category: "Tug Tow", Color: "#178003"},
}

// ShipTypeClass is used by the ShipTypes map to group and classify ship types.
type ShipTypeClass struct {
	GroupId int    `json:"groupId"`
	Class   string `json:"class"`
}

// ShipTypes maps the type of ship as an integer to its associated ShipTypeClass.
// Reference: https://www.navcen.uscg.gov/ais-class-a-static-voyage-message-5#TypeOfShip
// Reference: https://coast.noaa.gov/data/marinecadastre/ais/VesselTypeCodes2018.pdf
var ShipTypes = map[int]ShipTypeClass{
	0:   {GroupId: 3, Class: "not available"},
	1:   {GroupId: 4, Class: "Reserved"},
	2:   {GroupId: 4, Class: "Reserved"},
	3:   {GroupId: 4, Class: "Reserved"},
	4:   {GroupId: 4, Class: "Reserved"},
	5:   {GroupId: 4, Class: "Reserved"},
	6:   {GroupId: 4, Class: "Reserved"},
	7:   {GroupId: 4, Class: "Reserved"},
	8:   {GroupId: 4, Class: "Reserved"},
	9:   {GroupId: 4, Class: "Reserved"},
	10:  {GroupId: 4, Class: "Reserved"},
	11:  {GroupId: 4, Class: "Reserved"},
	12:  {GroupId: 4, Class: "Reserved"},
	13:  {GroupId: 4, Class: "Reserved"},
	14:  {GroupId: 4, Class: "Reserved"},
	15:  {GroupId: 4, Class: "Reserved"},
	16:  {GroupId: 4, Class: "Reserved"},
	17:  {GroupId: 4, Class: "Reserved"},
	18:  {GroupId: 4, Class: "Reserved"},
	19:  {GroupId: 4, Class: "Reserved"},
	20:  {GroupId: 4, Class: "Wing in ground (WIG), all ships of this type"},
	21:  {GroupId: 4, Class: "Wing in ground (WIG), hazardous category A"},
	22:  {GroupId: 4, Class: "Wing in ground (WIG), hazardous category B"},
	23:  {GroupId: 4, Class: "Wing in ground (WIG), hazardous category C"},
	24:  {GroupId: 4, Class: "Wing in ground (WIG), hazardous category D"},
	25:  {GroupId: 4, Class: "Wing in ground (WIG), reserved for future use"},
	26:  {GroupId: 4, Class: "Wing in ground (WIG), reserved for future use"},
	27:  {GroupId: 4, Class: "Wing in ground (WIG), reserved for future use"},
	28:  {GroupId: 4, Class: "Wing in ground (WIG), reserved for future use"},
	29:  {GroupId: 4, Class: "Wing in ground (WIG), reserved for future use"},
	30:  {GroupId: 1, Class: "Fishing"},
	31:  {GroupId: 8, Class: "Towing"},
	32:  {GroupId: 8, Class: "Towing: length exceeds 200m or breadth exceeds 25m"},
	33:  {GroupId: 4, Class: "Dredging or underwater operations"},
	34:  {GroupId: 4, Class: "Diving operations"},
	35:  {GroupId: 2, Class: "Military operations"},
	36:  {GroupId: 6, Class: "Sailing"},
	37:  {GroupId: 6, Class: "Pleasure Craft"},
	38:  {GroupId: 4, Class: "Reserved"},
	39:  {GroupId: 4, Class: "Reserved"},
	40:  {GroupId: 4, Class: "High speed craft (HSC), all ships of this type"},
	41:  {GroupId: 4, Class: "High speed craft (HSC), hazardous category A"},
	42:  {GroupId: 4, Class: "High speed craft (HSC), hazardous category B"},
	43:  {GroupId: 4, Class: "High speed craft (HSC), hazardous category C"},
	44:  {GroupId: 4, Class: "High speed craft (HSC), hazardous category D"},
	45:  {GroupId: 4, Class: "High speed craft (HSC), reserved for future use"},
	46:  {GroupId: 4, Class: "High speed craft (HSC), reserved for future use"},
	47:  {GroupId: 4, Class: "High speed craft (HSC), reserved for future use"},
	48:  {GroupId: 4, Class: "High speed craft (HSC), reserved for future use"},
	49:  {GroupId: 4, Class: "High speed craft (HSC), reserved for future use"},
	50:  {GroupId: 4, Class: "Pilot Vessel"},
	51:  {GroupId: 4, Class: "Search and Rescue vessel"},
	52:  {GroupId: 8, Class: "Tug"},
	53:  {GroupId: 4, Class: "Port Tender"},
	54:  {GroupId: 4, Class: "Anti-pollution equipment"},
	55:  {GroupId: 4, Class: "Law Enforcement"},
	56:  {GroupId: 4, Class: "Spare - for assignment to local vessel"},
	57:  {GroupId: 4, Class: "Spare - for assignment to local vessel"},
	58:  {GroupId: 4, Class: "Medical Transport"},
	59:  {GroupId: 4, Class: "Ship according to RR Resolution No. 18"},
	60:  {GroupId: 5, Class: "Passenger, all ships of this type"},
	61:  {GroupId: 5, Class: "Passenger, hazardous category A"},
	62:  {GroupId: 5, Class: "Passenger, hazardous category B"},
	63:  {GroupId: 5, Class: "Passenger, hazardous category C"},
	64:  {GroupId: 5, Class: "Passenger, hazardous category D"},
	65:  {GroupId: 5, Class: "Passenger, reserved for future use"},
	66:  {GroupId: 5, Class: "Passenger, reserved for future use"},
	67:  {GroupId: 5, Class: "Passenger, reserved for future use"},
	68:  {GroupId: 5, Class: "Passenger, reserved for future use"},
	69:  {GroupId: 5, Class: "Passenger, no additional information"},
	70:  {GroupId: 0, Class: "Cargo, all ships of this type"},
	71:  {GroupId: 0, Class: "Cargo, hazardous category A"},
	72:  {GroupId: 0, Class: "Cargo, hazardous category B"},
	73:  {GroupId: 0, Class: "Cargo, hazardous category C"},
	74:  {GroupId: 0, Class: "Cargo, hazardous category D"},
	75:  {GroupId: 0, Class: "Cargo, reserved for future use"},
	76:  {GroupId: 0, Class: "Cargo, reserved for future use"},
	77:  {GroupId: 0, Class: "Cargo, reserved for future use"},
	78:  {GroupId: 0, Class: "Cargo, reserved for future use"},
	79:  {GroupId: 0, Class: "Cargo, no additional information"},
	80:  {GroupId: 7, Class: "Tanker, all ships of this type"},
	81:  {GroupId: 7, Class: "Tanker, hazardous category A"},
	82:  {GroupId: 7, Class: "Tanker, hazardous category B"},
	83:  {GroupId: 7, Class: "Tanker, hazardous category C"},
	84:  {GroupId: 7, Class: "Tanker, hazardous category D"},
	85:  {GroupId: 7, Class: "Tanker, reserved for future use"},
	86:  {GroupId: 7, Class: "Tanker, reserved for future use"},
	87:  {GroupId: 7, Class: "Tanker, reserved for future use"},
	88:  {GroupId: 7, Class: "Tanker, reserved for future use"},
	89:  {GroupId: 7, Class: "Tanker, no additional information"},
	90:  {GroupId: 4, Class: "Other, all ships of this type"},
	91:  {GroupId: 4, Class: "Other, hazardous category A"},
	92:  {GroupId: 4, Class: "Other, hazardous category B"},
	93:  {GroupId: 4, Class: "Other, hazardous category C"},
	94:  {GroupId: 4, Class: "Other, hazardous category D"},
	95:  {GroupId: 4, Class: "Other, reserved for future use"},
	96:  {GroupId: 4, Class: "Other, reserved for future use"},
	97:  {GroupId: 4, Class: "Other, reserved for future use"},
	98:  {GroupId: 4, Class: "Other, reserved for future use"},
	99:  {GroupId: 4, Class: "Other, no additional information"},
	100: {GroupId: 4, Class: "reserved, for regional use"},
	101: {GroupId: 4, Class: "reserved, for regional use"},
	102: {GroupId: 4, Class: "reserved, for regional use"},
	103: {GroupId: 4, Class: "reserved, for regional use"},
	104: {GroupId: 4, Class: "reserved, for regional use"},
	105: {GroupId: 4, Class: "reserved, for regional use"},
	106: {GroupId: 4, Class: "reserved, for regional use"},
	107: {GroupId: 4, Class: "reserved, for regional use"},
	108: {GroupId: 4, Class: "reserved, for regional use"},
	109: {GroupId: 4, Class: "reserved, for regional use"},
	110: {GroupId: 4, Class: "reserved, for regional use"},
	111: {GroupId: 4, Class: "reserved, for regional use"},
	112: {GroupId: 4, Class: "reserved, for regional use"},
	113: {GroupId: 4, Class: "reserved, for regional use"},
	114: {GroupId: 4, Class: "reserved, for regional use"},
	115: {GroupId: 4, Class: "reserved, for regional use"},
	116: {GroupId: 4, Class: "reserved, for regional use"},
	117: {GroupId: 4, Class: "reserved, for regional use"},
	118: {GroupId: 4, Class: "reserved, for regional use"},
	119: {GroupId: 4, Class: "reserved, for regional use"},
	120: {GroupId: 4, Class: "reserved, for regional use"},
	121: {GroupId: 4, Class: "reserved, for regional use"},
	122: {GroupId: 4, Class: "reserved, for regional use"},
	123: {GroupId: 4, Class: "reserved, for regional use"},
	124: {GroupId: 4, Class: "reserved, for regional use"},
	125: {GroupId: 4, Class: "reserved, for regional use"},
	126: {GroupId: 4, Class: "reserved, for regional use"},
	127: {GroupId: 4, Class: "reserved, for regional use"},
	128: {GroupId: 4, Class: "reserved, for regional use"},
	129: {GroupId: 4, Class: "reserved, for regional use"},
	130: {GroupId: 4, Class: "reserved, for regional use"},
	131: {GroupId: 4, Class: "reserved, for regional use"},
	132: {GroupId: 4, Class: "reserved, for regional use"},
	133: {GroupId: 4, Class: "reserved, for regional use"},
	134: {GroupId: 4, Class: "reserved, for regional use"},
	135: {GroupId: 4, Class: "reserved, for regional use"},
	136: {GroupId: 4, Class: "reserved, for regional use"},
	137: {GroupId: 4, Class: "reserved, for regional use"},
	138: {GroupId: 4, Class: "reserved, for regional use"},
	139: {GroupId: 4, Class: "reserved, for regional use"},
	140: {GroupId: 4, Class: "reserved, for regional use"},
	141: {GroupId: 4, Class: "reserved, for regional use"},
	142: {GroupId: 4, Class: "reserved, for regional use"},
	143: {GroupId: 4, Class: "reserved, for regional use"},
	144: {GroupId: 4, Class: "reserved, for regional use"},
	145: {GroupId: 4, Class: "reserved, for regional use"},
	146: {GroupId: 4, Class: "reserved, for regional use"},
	147: {GroupId: 4, Class: "reserved, for regional use"},
	148: {GroupId: 4, Class: "reserved, for regional use"},
	149: {GroupId: 4, Class: "reserved, for regional use"},
	150: {GroupId: 4, Class: "reserved, for regional use"},
	151: {GroupId: 4, Class: "reserved, for regional use"},
	152: {GroupId: 4, Class: "reserved, for regional use"},
	153: {GroupId: 4, Class: "reserved, for regional use"},
	154: {GroupId: 4, Class: "reserved, for regional use"},
	155: {GroupId: 4, Class: "reserved, for regional use"},
	156: {GroupId: 4, Class: "reserved, for regional use"},
	157: {GroupId: 4, Class: "reserved, for regional use"},
	158: {GroupId: 4, Class: "reserved, for regional use"},
	159: {GroupId: 4, Class: "reserved, for regional use"},
	160: {GroupId: 4, Class: "reserved, for regional use"},
	161: {GroupId: 4, Class: "reserved, for regional use"},
	162: {GroupId: 4, Class: "reserved, for regional use"},
	163: {GroupId: 4, Class: "reserved, for regional use"},
	164: {GroupId: 4, Class: "reserved, for regional use"},
	165: {GroupId: 4, Class: "reserved, for regional use"},
	166: {GroupId: 4, Class: "reserved, for regional use"},
	167: {GroupId: 4, Class: "reserved, for regional use"},
	168: {GroupId: 4, Class: "reserved, for regional use"},
	169: {GroupId: 4, Class: "reserved, for regional use"},
	170: {GroupId: 4, Class: "reserved, for regional use"},
	171: {GroupId: 4, Class: "reserved, for regional use"},
	172: {GroupId: 4, Class: "reserved, for regional use"},
	173: {GroupId: 4, Class: "reserved, for regional use"},
	174: {GroupId: 4, Class: "reserved, for regional use"},
	175: {GroupId: 4, Class: "reserved, for regional use"},
	176: {GroupId: 4, Class: "reserved, for regional use"},
	177: {GroupId: 4, Class: "reserved, for regional use"},
	178: {GroupId: 4, Class: "reserved, for regional use"},
	179: {GroupId: 4, Class: "reserved, for regional use"},
	180: {GroupId: 4, Class: "reserved, for regional use"},
	181: {GroupId: 4, Class: "reserved, for regional use"},
	182: {GroupId: 4, Class: "reserved, for regional use"},
	183: {GroupId: 4, Class: "reserved, for regional use"},
	184: {GroupId: 4, Class: "reserved, for regional use"},
	185: {GroupId: 4, Class: "reserved, for regional use"},
	186: {GroupId: 4, Class: "reserved, for regional use"},
	187: {GroupId: 4, Class: "reserved, for regional use"},
	188: {GroupId: 4, Class: "reserved, for regional use"},
	189: {GroupId: 4, Class: "reserved, for regional use"},
	190: {GroupId: 4, Class: "reserved, for regional use"},
	191: {GroupId: 4, Class: "reserved, for regional use"},
	192: {GroupId: 4, Class: "reserved, for regional use"},
	193: {GroupId: 4, Class: "reserved, for regional use"},
	194: {GroupId: 4, Class: "reserved, for regional use"},
	195: {GroupId: 4, Class: "reserved, for regional use"},
	196: {GroupId: 4, Class: "reserved, for regional use"},
	197: {GroupId: 4, Class: "reserved, for regional use"},
	198: {GroupId: 4, Class: "reserved, for regional use"},
	199: {GroupId: 4, Class: "reserved, for regional use"},
	200: {GroupId: 4, Class: "reserved, for future use"},
	201: {GroupId: 4, Class: "reserved, for future use"},
	202: {GroupId: 4, Class: "reserved, for future use"},
	203: {GroupId: 4, Class: "reserved, for future use"},
	204: {GroupId: 4, Class: "reserved, for future use"},
	205: {GroupId: 4, Class: "reserved, for future use"},
	206: {GroupId: 4, Class: "reserved, for future use"},
	207: {GroupId: 4, Class: "reserved, for future use"},
	208: {GroupId: 4, Class: "reserved, for future use"},
	209: {GroupId: 4, Class: "reserved, for future use"},
	210: {GroupId: 4, Class: "reserved, for future use"},
	211: {GroupId: 4, Class: "reserved, for future use"},
	212: {GroupId: 4, Class: "reserved, for future use"},
	213: {GroupId: 4, Class: "reserved, for future use"},
	214: {GroupId: 4, Class: "reserved, for future use"},
	215: {GroupId: 4, Class: "reserved, for future use"},
	216: {GroupId: 4, Class: "reserved, for future use"},
	217: {GroupId: 4, Class: "reserved, for future use"},
	218: {GroupId: 4, Class: "reserved, for future use"},
	219: {GroupId: 4, Class: "reserved, for future use"},
	220: {GroupId: 4, Class: "reserved, for future use"},
	221: {GroupId: 4, Class: "reserved, for future use"},
	222: {GroupId: 4, Class: "reserved, for future use"},
	223: {GroupId: 4, Class: "reserved, for future use"},
	224: {GroupId: 4, Class: "reserved, for future use"},
	225: {GroupId: 4, Class: "reserved, for future use"},
	226: {GroupId: 4, Class: "reserved, for future use"},
	227: {GroupId: 4, Class: "reserved, for future use"},
	228: {GroupId: 4, Class: "reserved, for future use"},
	229: {GroupId: 4, Class: "reserved, for future use"},
	230: {GroupId: 4, Class: "reserved, for future use"},
	231: {GroupId: 4, Class: "reserved, for future use"},
	232: {GroupId: 4, Class: "reserved, for future use"},
	233: {GroupId: 4, Class: "reserved, for future use"},
	234: {GroupId: 4, Class: "reserved, for future use"},
	235: {GroupId: 4, Class: "reserved, for future use"},
	236: {GroupId: 4, Class: "reserved, for future use"},
	237: {GroupId: 4, Class: "reserved, for future use"},
	238: {GroupId: 4, Class: "reserved, for future use"},
	239: {GroupId: 4, Class: "reserved, for future use"},
	240: {GroupId: 4, Class: "reserved, for future use"},
	241: {GroupId: 4, Class: "reserved, for future use"},
	242: {GroupId: 4, Class: "reserved, for future use"},
	243: {GroupId: 4, Class: "reserved, for future use"},
	244: {GroupId: 4, Class: "reserved, for future use"},
	245: {GroupId: 4, Class: "reserved, for future use"},
	246: {GroupId: 4, Class: "reserved, for future use"},
	247: {GroupId: 4, Class: "reserved, for future use"},
	248: {GroupId: 4, Class: "reserved, for future use"},
	249: {GroupId: 4, Class: "reserved, for future use"},
	250: {GroupId: 4, Class: "reserved, for future use"},
	251: {GroupId: 4, Class: "reserved, for future use"},
	252: {GroupId: 4, Class: "reserved, for future use"},
	253: {GroupId: 4, Class: "reserved, for future use"},
	254: {GroupId: 4, Class: "reserved, for future use"},
	255: {GroupId: 4, Class: "reserved, for future use"},
}
